### ISSUE TITLE
Segfault in tmxrasterizer

### ISSUE THREAD

**Issue by kivutar** [mapeditor/tiled#3804]
**Describe the bug**

I was trying to export a tmx to png when I noticed a segfault.

**To Reproduce**
1. Be on linux + gnome + wayland
2. Run a command like `tmxrasterizer --hide-layer objects res/castle1.tmx res/castle1.png`

```
Starting program: /usr/bin/tmxrasterizer --hide-layer objects res/castle1.tmx res/castle1.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2fff6c0 (LWP 225822)]
[New Thread 0x7ffff1e166c0 (LWP 225823)]
[New Thread 0x7ffff16156c0 (LWP 225824)]

Thread 1 "tmxrasterizer" received signal SIGSEGV, Segmentation fault.
0x00007ffff77b210a in QGuiApplicationPrivate::setPalette(QPalette const&) () from /usr/lib/libQt6Gui.so.6
(gdb) bt
#0  0x00007ffff77b210a in QGuiApplicationPrivate::setPalette(QPalette const&) () from /usr/lib/libQt6Gui.so.6
#1  0x00007ffff77b3913 in QGuiApplicationPrivate::updatePalette() () from /usr/lib/libQt6Gui.so.6
#2  0x00007ffff77a910f in QGuiApplicationPrivate::init() () from /usr/lib/libQt6Gui.so.6
#3  0x00007ffff77a0efb in QGuiApplication::QGuiApplication(int&, char**, int) () from /usr/lib/libQt6Gui.so.6
#4  0x0000555555558575 in ?? ()
#5  0x00007ffff6a39850 in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff6a3990a in __libc_start_main () from /usr/lib/libc.so.6
#7  0x000055555555a045 in ?? ()
(gdb)
```

**Expected behavior**

**Media**
If applicable, add screenshots or videos to help explain your problem.

**Specifications:**
 - OS: Arch Linux
 - Tiled Version: 1.10.1

Also:

```
tmxrasterizer --version
Erreur de segmentation (core dumped
```

But:

```
tiled --version
Tiled 1.10.1
```

Note that Tiled works fine and can export maps. But I need to run tmxrasterizer in my Makefile on a whole folder of assets.

**Comment by bjorn** [comment]
Hmm, according to the backtrace, no Tiled code is involved in the crash. Is it still happening, @kivutar?
